/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.9.1.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as advanceBall from "../advanceBall";
import type * as countDown from "../countDown";
import type * as getBall from "../getBall";
import type * as getById from "../getById";
import type * as getGame from "../getGame";
import type * as getPaddle from "../getPaddle";
import type * as joinOrCreateGame from "../joinOrCreateGame";
import type * as movePaddle from "../movePaddle";
import type * as updateGameStatus from "../updateGameStatus";
import type * as updatePing from "../updatePing";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  advanceBall: typeof advanceBall;
  countDown: typeof countDown;
  getBall: typeof getBall;
  getById: typeof getById;
  getGame: typeof getGame;
  getPaddle: typeof getPaddle;
  joinOrCreateGame: typeof joinOrCreateGame;
  movePaddle: typeof movePaddle;
  updateGameStatus: typeof updateGameStatus;
  updatePing: typeof updatePing;
}>;
